/// Flutter icons Wecome_page
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Wecome_page
///      fonts:
///       - asset: fonts/Wecome_page.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Wecome_page {
  Wecome_page._();

  static const _kFontFam = 'Wecome_page';
  static const String? _kFontPkg = null;

  static const IconData la_money_bill = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData game_icons_money_stack = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_money = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lni_lni_users__1_ = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
